### ISSUE TITLE
解題進度顯示錯誤

### ISSUE THREAD

**Issue by asef18766** [w33d-ctf/Escape-Room#3]
rt, 若單一使用者重複上傳flag時, 將會重複顯示該題, 
應只顯示最高難度之單一flag解法
ex: pA_easy, pB_hard, ...
附圖狀況為交一次easy後再交一次hard
![image](https://user-images.githubusercontent.com/40972942/118169566-ab116680-b45b-11eb-90ae-9fd4b3ea45a6.png)

**Comment by as535364** [comment]
我以為同時間只會玩一套題目 (easy, hard)？

**Comment by as535364** [comment]
目前只有移除重複標籤，不會做 hard 優先於 easy 的判斷
